return {
    ---@param cutscene WorldCutscene
    
    encounter = function(cutscene, event)
        local susie = cutscene:getCharacter("susie")
        local ralsei = cutscene:getCharacter("ralsei")
        local cam_x, cam_y = cutscene:getMarker("cam")
        cutscene:detachCamera()
        cutscene:detachFollowers()
        cutscene:panTo(cam_x, cam_y)
        cutscene:walkTo("kris", "krisloc", 1)
        cutscene:walkTo("susie", "susieloc", 1)
        cutscene:wait(cutscene:walkTo("ralsei", "ralseiloc", 1))
        cutscene:setSpeaker(susie)
        cutscene:text("* Finally.[wait:2]\n* Took long enough to get in here", "nervous_side")
        cutscene:setSpeaker(ralsei)
        cutscene:text("* Odd...[wait:2]\n* All that's inside is...", "smile_side")
        cutscene:setSpeaker(susie)
        cutscene:text("* Tenna...?", "surprise")
        Assets.playSound("impact")
        cutscene:wait(1)
        cutscene:setSpeaker()
        cutscene:text("* YOU MUST LEAVE.")
        cutscene:setSpeaker(susie)
        cutscene:text("* What? [wait:1]\n* Tenna come on, lets get you out of here...", "nervous")
        cutscene:setSpeaker(ralsei)
        cutscene:text("* Susie... i dont think that's-[next:true]", "pensive")
        cutscene:setSpeaker()
        ralsei:setSprite("battle/hurt_1")
        Assets.playSound("impact")
        cutscene:text("* NO.[wait:2]\n* IT IS TOO LATE.")
        ralsei:setSprite("walk/right_1")
        cutscene:text("* IT FEEDS ON ATTENTION.[wait:1]\n* AND IT HAS BEEN STARVING.")
        Assets.playSound("hurt")
        cutscene:text("* FOR A LONG.[wait:10]\n* [sound:hurt]LONG.[wait:10]\n* TIM[sound:hurt][next:true]")
        Assets.playSound("impact")
        susie:setSprite("shock_right")
    end
}